# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



In [1]:
import numpy as np

## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

We've already downloaded the dataset, its in this folder. So let's open it up. 

In [2]:
from sklearn.datasets import load_iris

C:\Users\pwalsh\Anaconda3\envs\nlp_course\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
C:\Users\pwalsh\Anaconda3\envs\nlp_course\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [3]:
iris = load_iris()

C:\Users\pwalsh\Anaconda3\envs\nlp_course\lib\site-packages\sklearn\datasets\base.py:242: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
C:\Users\pwalsh\Anaconda3\envs\nlp_course\lib\site-packages\sklearn\datasets\base.py:246: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
X # (sepal length, sepal width, petal length, petal width)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Convert to categorical labeling system (One-Hot Encoding)

In [10]:
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [17]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [18]:
from sklearn.preprocessing import MinMaxScaler

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [19]:
scaler = MinMaxScaler()

In [20]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler.transform(X_train)

In [22]:
scaled_X_test = scaler.transform(X_test)

## Create model  and add layers to model

In [23]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
model = Sequential()
# .add(layer_name(num of neurons, num of features, activation function))
model.add(Dense(units=8,input_dim=4,activation='relu'))  # hidden layer
model.add(Dense(units=8,input_dim=4,activation='relu'))  # hidden layer
model.add(Dense(units=3,activation='softmax'))  # output layer
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


## Train model

In [26]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.1688 - accuracy: 0.2800 - 807ms/epoch - 202ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1590 - accuracy: 0.2900 - 13ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1504 - accuracy: 0.2900 - 13ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1426 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1352 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1278 - accuracy: 0.3100 - 17ms/epoch - 4ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1206 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1137 - accuracy: 0.3100 - 22ms/epoch - 6ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1071 - accuracy: 0.3100 - 19ms/epoch - 5ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1006 - accuracy: 0.3100 - 13ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0941 - accuracy: 0.3100 - 13ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0878 - accuracy: 0.3100 - 14ms/epoch - 4ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0817 - accurac

Epoch 104/150
4/4 - 0s - loss: 0.5521 - accuracy: 0.9400 - 12ms/epoch - 3ms/step
Epoch 105/150
4/4 - 0s - loss: 0.5490 - accuracy: 0.9300 - 10ms/epoch - 3ms/step
Epoch 106/150
4/4 - 0s - loss: 0.5457 - accuracy: 0.9000 - 11ms/epoch - 3ms/step
Epoch 107/150
4/4 - 0s - loss: 0.5425 - accuracy: 0.8800 - 15ms/epoch - 4ms/step
Epoch 108/150
4/4 - 0s - loss: 0.5397 - accuracy: 0.8600 - 12ms/epoch - 3ms/step
Epoch 109/150
4/4 - 0s - loss: 0.5368 - accuracy: 0.8200 - 9ms/epoch - 2ms/step
Epoch 110/150
4/4 - 0s - loss: 0.5341 - accuracy: 0.8200 - 11ms/epoch - 3ms/step
Epoch 111/150
4/4 - 0s - loss: 0.5313 - accuracy: 0.8200 - 10ms/epoch - 3ms/step
Epoch 112/150
4/4 - 0s - loss: 0.5287 - accuracy: 0.8100 - 20ms/epoch - 5ms/step
Epoch 113/150
4/4 - 0s - loss: 0.5259 - accuracy: 0.8000 - 13ms/epoch - 3ms/step
Epoch 114/150
4/4 - 0s - loss: 0.5234 - accuracy: 0.8000 - 18ms/epoch - 5ms/step
Epoch 115/150
4/4 - 0s - loss: 0.5209 - accuracy: 0.8200 - 11ms/epoch - 3ms/step
Epoch 116/150
4/4 - 0s - loss

## Test model

In [27]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [28]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 5ms/step


array([[3.93695682e-02, 4.76471245e-01, 4.84159201e-01],
       [9.84910727e-01, 1.31454496e-02, 1.94384076e-03],
       [8.48339871e-03, 3.28120232e-01, 6.63396358e-01],
       [4.75969948e-02, 4.89788681e-01, 4.62614357e-01],
       [2.52100080e-02, 4.56029505e-01, 5.18760562e-01],
       [9.70267296e-01, 2.49806736e-02, 4.75201383e-03],
       [1.44765511e-01, 5.22280931e-01, 3.32953632e-01],
       [1.23873297e-02, 4.05636996e-01, 5.81975698e-01],
       [2.77639832e-02, 4.19963479e-01, 5.52272558e-01],
       [8.01111013e-02, 5.15187681e-01, 4.04701293e-01],
       [2.31456608e-02, 4.51545805e-01, 5.25308549e-01],
       [9.67910826e-01, 2.63044462e-02, 5.78477653e-03],
       [9.86282408e-01, 1.18669206e-02, 1.85074820e-03],
       [9.69873667e-01, 2.48747356e-02, 5.25156176e-03],
       [9.89073813e-01, 9.55530722e-03, 1.37095666e-03],
       [5.63425422e-02, 5.20895779e-01, 4.22761708e-01],
       [1.25899855e-02, 3.80470663e-01, 6.06939435e-01],
       [7.28756487e-02, 4.98084

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [29]:
predictions = np.argmax(model.predict(scaled_X_test), axis=1)

2/2 [==============================] - 0s 6ms/step


In [30]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [32]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 16]], dtype=int64)

In [33]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.80      0.89        15
           2       0.84      1.00      0.91        16

   micro avg       0.94      0.94      0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.95      0.94      0.94        50



In [34]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.94

## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [35]:
model.save('my_first_model.h5')

Reload model from saved model

In [36]:
from keras.models import load_model

In [37]:
new_model = load_model('my_first_model.h5')

In [38]:
new_model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step


array([[3.93695682e-02, 4.76471245e-01, 4.84159201e-01],
       [9.84910727e-01, 1.31454496e-02, 1.94384076e-03],
       [8.48339871e-03, 3.28120232e-01, 6.63396358e-01],
       [4.75969948e-02, 4.89788681e-01, 4.62614357e-01],
       [2.52100080e-02, 4.56029505e-01, 5.18760562e-01],
       [9.70267296e-01, 2.49806736e-02, 4.75201383e-03],
       [1.44765511e-01, 5.22280931e-01, 3.32953632e-01],
       [1.23873297e-02, 4.05636996e-01, 5.81975698e-01],
       [2.77639832e-02, 4.19963479e-01, 5.52272558e-01],
       [8.01111013e-02, 5.15187681e-01, 4.04701293e-01],
       [2.31456608e-02, 4.51545805e-01, 5.25308549e-01],
       [9.67910826e-01, 2.63044462e-02, 5.78477653e-03],
       [9.86282408e-01, 1.18669206e-02, 1.85074820e-03],
       [9.69873667e-01, 2.48747356e-02, 5.25156176e-03],
       [9.89073813e-01, 9.55530722e-03, 1.37095666e-03],
       [5.63425422e-02, 5.20895779e-01, 4.22761708e-01],
       [1.25899855e-02, 3.80470663e-01, 6.06939435e-01],
       [7.28756487e-02, 4.98084